### ISSUE TITLE
Importing app.py to userauth .py files

### ISSUE THREAD

**Issue by normit581** [seanlixu/CITS3403-RequestBoard#10]
I am getting an error in which when I try import app from app.py I get an error saying module not found. Code for this is 
from app import app.

Code:
![image](https://github.com/seanlixu/CITS3403-RequestBoard/assets/139199443/1b0c1f24-29ff-4ccb-ac50-724d7dfb0b77)

Error:
![image](https://github.com/seanlixu/CITS3403-RequestBoard/assets/139199443/15bad06b-a4c8-4276-aec4-38ca1bb23580)

File structure:
![image](https://github.com/seanlixu/CITS3403-RequestBoard/assets/139199443/baaae673-16e7-4efc-897d-a484775f8413)

Anyone know if the issue is the name of the directory being called app and the app.py file is a factor?
If not why would the modulenotfounderror be occuring?

Thanks

**Comment by paulmmaingi** [comment]
I believe its because the directory is now named userauth and not app. When you try and import the flask instance created with: `app = Flask(__name__)`, you are using `from app import app`, here the first `app` being the module/directory name. A simple fix I think would be `from userauth import app`.

**Comment by paulmmaingi** [comment]
**ISSUE SOLVED**

@normit581 redid the file structure and made sure the imports were valid and the code was working.
